#!/usr/bin/env bash
# Installs system packages and external tools for the detected OS

set -euo pipefail

DOTFILES_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

# source helper functions
source "$DOTFILES_DIR/lib/detect-os.sh"
source "$DOTFILES_DIR/lib/log.sh"

# detect os
OS="$(detect_os)"

title "Script Info"
info "OS: $OS"

# TODO: uncomment below once install functions have been renamed
#
# source OS-specific installers
# source "$DOTFILES_DIR/installers/$os.sh"
# source "$DOTFILES_DIR/installers/external/$os.sh"

# source post-install
source "$DOTFILES_DIR/installers/post-install.sh"

# start install
title "Starting Package Install"

# TODO: replace switch case with an import of each of the functions using the OS
#       - Example:
#           - source "$DOTFILES_DIR/installers/$os.sh"
#           - source "$DOTFILES_DIR/installers/external/$os.sh"
#
# TODO: rename install_${os} functions to something more generic, like install_packages (so the switch case won't be necessary)
case "$OS" in
    debian)
        source "$DOTFILES_DIR/installers/debian.sh"
        source "$DOTFILES_DIR/installers/external/debian.sh"
        install_debian
        ;;
    arch)
        source "$DOTFILES_DIR/installers/arch.sh"
        source "$DOTFILES_DIR/installers/external/arch.sh"
        install_arch
        ;;
    macos)
        source "$DOTFILES_DIR/installers/macos.sh"
        source "$DOTFILES_DIR/installers/external/macos.sh"
        install_macos
        ;;
    *)
        info "Unsupported OS: $OS" >&2
        exit 1
        ;;
esac

# TODO: look into if there are different post-installers needed for each OS

# post-install setup after package and external tool instalation
run_post_install
