#!/usr/bin/env bash
# Stows the default OS-specific set of dotfiles modules into $HOME

set -euo pipefail

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STOW_MODULES_DIR="$DOTFILES_DIR/stow-modules"

# --- Source helper functions ---
source "${DOTFILES_DIR}/lib/log.sh"
source "${DOTFILES_DIR}/lib/detect-os.sh"
source "${DOTFILES_DIR}/lib/stow-modules.sh"
source "${DOTFILES_DIR}/lib/stow-actions.sh"

# --- OS info ---
os="$(detect_os)"
info "OS: $os"

# --- Source OS-specific stow modules ---
source "$STOW_MODULES_DIR/common.sh"
source "$STOW_MODULES_DIR/$os.sh"

# --- Stow config files ---
stow_all_modules \
    "${COMMON_MODULES[@]}" \
    "${OS_MODULES[@]}"
