gui:
  commandLogSize: 8
  scrollHeight: 4
  scrollPastBottom: false
  showFileTree: true
  theme:
    activeBorderColor:
      - '#a9b665'
      - bold
    inactiveBorderColor:
      - '#7c6f64'
    searchingActiveBorderColor:
      - '#d8a657'
      - bold

    optionsTextColor:
      - '#d8a657'
    defaultFgColor:
      - '#d4be98'

    selectedLineBgColor:
      - '#404946'
    inactiveViewSelectedLineBgColor:
      - '#1d2021'

    cherryPickedCommitFgColor:
      - '#fbf1c7'
    cherryPickedCommitBgColor:
      - '#1f302d'

    markedBaseCommitFgColor:
      - '#f9f5d7'
    markedBaseCommitBgColor:
      - '#473c29'

    unstagedChangesColor:
      - '#ea6962'
os:
  editPreset: "nvim"
keybinding:
  universal:
    quit: "q"
    quit-alt1: "<disabled>"
    return: "<c-c>"
