gui:
  commandLogSize: 8
  scrollHeight: 4
  scrollPastBottom: false
  showFileTree: true
  theme:
    activeBorderColor:
      - '#9da866'
      - bold
    inactiveBorderColor:
      - '#665c54'
    searchingActiveBorderColor:
      - '#c8954f'
      - bold

    optionsTextColor:
      - '#c8954f'
    defaultFgColor:
      - '#c7b58a'

    selectedLineBgColor:
      - '#374141'
    inactiveViewSelectedLineBgColor:
      - '#1d2021'

    cherryPickedCommitFgColor:
      - '#ebdbb2'
    cherryPickedCommitBgColor:
      - '#1b2e2a'

    markedBaseCommitFgColor:
      - '#ebdbb2'
    markedBaseCommitBgColor:
      - '#3d3324'

    unstagedChangesColor:
      - '#d85f59'
os:
  editPreset: "nvim"
keybinding:
  universal:
    quit: "q"
    quit-alt1: "<disabled>"
    return: "<c-c>"
