gui:
  commandLogSize: 8
  scrollHeight: 4
  scrollPastBottom: false
  showFileTree: true
  theme:
    selectedLineBgColor:
      - '#3c3836'
    inactiveViewSelectedLineBgColor:
      - '#32302f'
os:
  editPreset: "nvim"
keybinding:
  universal:
    quit: "q"
    quit-alt1: "<disabled>"
    return: "<c-c>"
